#!/usr/bin/env python3
"""Generate README.md from apps.csv and repo-meta.json.

Run from the site root whenever the gallery content changes:
    python3 scripts/generate_readme.py

The README is a markdown mirror of the live portfolio at
https://thecont1.github.io/ (also served at https://apps.thecontrarian.in/).
It is regenerated from the same data files the browser renders, so the
profile README never drifts from the curated portfolio.

The generated README is also pushed to the thecont1/thecont1 profile repo
by .github/workflows/sync-profile-readme.yml so GitHub's special profile
README stays in sync with this portfolio automatically.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "apps.csv"
META_PATH = ROOT / "repo-meta.json"
OUTPUT_PATH = ROOT / "README.md"

SITE_URL = "https://apps.thecontrarian.in/"
GITHUB_URL = "https://github.com/thecont1"


def clean(value: str | None) -> str:
    return " ".join((value or "").split())


def load_apps() -> list[dict[str, str]]:
    if not CSV_PATH.exists():
        raise FileNotFoundError(f"Missing {CSV_PATH}")
    with CSV_PATH.open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))
    if not rows or "app_name" not in rows[0] or "repo_url" not in rows[0]:
        raise ValueError("apps.csv must contain app_name and repo_url columns")
    return rows


def load_meta() -> dict[str, dict[str, object]]:
    if not META_PATH.exists():
        raise FileNotFoundError(f"Missing {META_PATH}")
    return json.loads(META_PATH.read_text(encoding="utf-8"))


def badge(label: str) -> str:
    """Render a static markdown badge for a tech label."""
    return f"`{label}`"


def render_app(row: dict[str, str], meta: dict[str, object]) -> list[str]:
    name = clean(row.get("app_name"))
    repo_url = clean(row.get("repo_url"))
    entry = meta.get(repo_url, {})
    description = clean(entry.get("description")) or "A small, thoughtful tool by Mahesh Shantaram."
    homepage = clean(entry.get("homepage")) or None
    tech_stack = entry.get("tech_stack") or entry.get("languages") or []
    if not isinstance(tech_stack, list):
        tech_stack = []

    lines: list[str] = []
    title = f"### [{name}]({repo_url})"
    if homepage:
        title += f" · [live]({homepage})"
    lines.append(title)
    lines.append("")
    lines.append(description)
    lines.append("")
    if tech_stack:
        lines.append(" ".join(badge(str(item)) for item in tech_stack))
        lines.append("")
    return lines


def render_readme(apps: list[dict[str, str]], meta: dict[str, dict[str, object]]) -> str:
    out: list[str] = []
    out.append("# Apps by Mahesh Shantaram")
    out.append("")
    out.append(
        "A working shelf of small experiments, civic tools and data "
        "visualisations for the public good. This README is generated "
        f"from `apps.csv` and `repo-meta.json` — see the live site at {SITE_URL}"
    )
    out.append("")
    out.append(f"Source: [{GITHUB_URL}/thecont1.github.io]({GITHUB_URL}/thecont1.github.io)")
    out.append("")
    out.append("---")
    out.append("")

    for row in apps:
        out.extend(render_app(row, meta))
        out.append("---")
        out.append("")

    out.append("## Colophon")
    out.append("")
    out.append(
        "This README is auto-generated by `scripts/generate_readme.py`. "
        "Edit `apps.csv` (and refresh `repo-meta.json` with "
        "`scripts/refresh_repo_meta.py`) and re-run the generator to update it. "
        "A GitHub Actions workflow keeps the profile README at "
        f"[{GITHUB_URL}/thecont1]({GITHUB_URL}/thecont1) in sync automatically."
    )
    out.append("")
    return "\n".join(out)


def main() -> int:
    try:
        apps = load_apps()
        meta = load_meta()
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    readme = render_readme(apps, meta)
    OUTPUT_PATH.write_text(readme, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(apps)} apps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
